### ISSUE TITLE
Implement support for 440EP CPU

### ISSUE THREAD

**Issue by GoogleCodeExporter** [khval/mplayer-amigaos#15]
```
- Compile a specific version of MPlayer with the HAVE_PPC4XX set to 1, and add 
-mcpu=440fp
- Implement a way to handle this automatically on the SVN - by creating a 
branch?
- Implement the define under the automatic CPU detect
```

Original issue reported on code.google.com by `varthal...@gmail.com` on 3 Mar 2011 at 10:56

**Comment by khval** [comment]
I'm not going to do this, too much work.
It be better if some Assembler optimized the FFMPEG arch PPC code.
(I'm not going to do that, too much work, and I have AltiVec, so I don't need it.)
