### ISSUE TITLE
Reimplementing the MPlayer menu from the old code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [khval/mplayer-amigaos#26]
```
In order to (step by step) completing the merge with the original version you 
should reimplement the code's menu and the associate functionalities
```

Original issue reported on code.google.com by `s.hawam...@gmail.com` on 19 May 2014 at 4:17

**Comment by khval** [comment]
This one is completed, I did not use code from old Mplayer, 
I have reorganized the code, from old mplayer, and made few of menu options async, so the video does not stop while you're selecting file to play. it's been tested and working on beta test forum.
