### ISSUE TITLE
Adding SCREENSHOTDIR and EXTPATTERN tooltypes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [khval/mplayer-amigaos#34]
```
Added two tooltypes SCREENSHOTDIR and EXTPATTERN to change the directory where 
to save the screenshots and the ASL pattern of the MPlayer file requester

(That 2 tooltypes is availible on the afxgroup version)
```

Original issue reported on code.google.com by `s.hawam...@gmail.com` on 21 May 2014 at 11:21

**Comment by khval** [comment]
This one is redone, I have not used tooltypes for mplayer options, 
mplayer has config file and arguments for this, if should support tooltypes. Then it should support all mplayer options, not just 1 or 2.
Anyway setting extpattern and setting screenshotdir can be done, and is working.
